# Prova

Com base no censo demografico de 2022 (https://www.ibge.gov.br/estatisticas/sociais/populacao/22827-censo-demografico-2022.html?edicao=38166&t=resultadosLinks to an external site.), baixe o arquivo  População por idade e sexo referente a seu estado de nascimento e faça:

a) Faça um programa em python que identifique qual a faixa etaria possui mais pessoas entre homens e mulheres.

b) Faça um programa python que com base na sua faixa etária e sexo identifique o municipio com mais pessoas.

c) Faça um programa python que com base na sua faixa etária e sexo identifique o municipio com menos pessoas.

d) Faça um programa em python que com base no seu municipio de nascimento identifique a maior faixa etária em anos  entre homens e mulheres.

e) Faça um programa em python que gere dois arquivos um em .xlsx e o outro .json com o resultado das questões acima e salve no  data-lake-turma6-puc/Links to an external site.Prova/

com seu nome a extensão de cada arquivo.

ex: nelson_junior.xlxs, nelson_junior.json

 

ob. O arquivo do Estado de  MG está em arquivos

### Preparação dos dados

In [140]:
import pandas as pd
df = pd.read_excel('../../Datasets/tabela9514_UF_MUN_MG.xlsx')
df

,"Tabela 9514 - População residente, por sexo, idade e forma de declaração da idade",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67
0,Variável - População residente (Pessoas),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Unidade da Federação e Município,Forma de declaração da idade,Ano x Sexo x Idade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Total,0 a 4 anos,5 a 9 anos,10 a 14 anos,15 a 19 anos,20 a 24 anos,25 a 29 anos,30 a 34 anos,...,55 a 59 anos,60 a 64 anos,65 a 69 anos,70 a 74 anos,75 a 79 anos,80 a 84 anos,85 a 89 anos,90 a 94 anos,95 a 99 anos,100 anos ou mais
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,Virgolândia (MG),Total,4552,237,269,313,297,281,237,290,...,188,143,120,105,79,54,48,26,7,3
856,Visconde do Rio Branco (MG),Total,39160,2418,2461,2455,2382,2768,2917,2911,...,1342,1160,874,695,441,332,215,103,27,4
857,Volta Grande (MG),Total,4443,250,267,260,302,318,289,313,...,148,141,132,87,56,45,31,12,5,3
858,Wenceslau Braz (MG),Total,2356,118,117,134,166,142,123,141,...,98,70,73,56,38,20,14,4,1,-
859,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
# Identificar os índices das colunas para 'Homens' e 'Mulheres'
# Identificar os índices das colunas para 'Homens' e 'Mulheres'
index_homens_pos = df.columns.get_loc((df.loc[3] == 'Homens').idxmax())
index_mulheres_pos = df.columns.get_loc((df.loc[3] == 'Mulheres').idxmax())
print(index_mulheres_pos)

# Selecionar as colunas de 'Homens' até uma posição antes de 'Mulheres'
df_homens = df.iloc[:-1, index_homens_pos:index_mulheres_pos]
df_mulheres = df.iloc[:-1, index_mulheres_pos:]

df_homens = df_homens.iloc[4:]
df_mulheres = df_mulheres.iloc[4:]
# Tornar a primeira linha os nomes das colunas
df_homens.columns = df_homens.iloc[0]
df_mulheres.columns = df_mulheres.iloc[0]
df_homens = df_homens[1:]
df_mulheres = df_mulheres[1:]

# Redefinir os índices do DataFrame
df_homens.reset_index(drop=True, inplace=True)
df_mulheres.reset_index(drop=True, inplace=True)

46

In [142]:
df_homens.tail()

4,Total,0 a 4 anos,5 a 9 anos,10 a 14 anos,15 a 19 anos,20 a 24 anos,25 a 29 anos,30 a 34 anos,35 a 39 anos,40 a 44 anos,...,55 a 59 anos,60 a 64 anos,65 a 69 anos,70 a 74 anos,75 a 79 anos,80 a 84 anos,85 a 89 anos,90 a 94 anos,95 a 99 anos,100 anos ou mais
849,5051,307,346,344,358,344,347,351,338,347,...,341,304,269,151,125,76,37,28,4,-
850,2209,111,140,164,132,160,117,135,129,135,...,157,162,101,83,61,51,30,18,3,1
851,19053,1219,1263,1300,1205,1392,1414,1418,1525,1558,...,1204,1035,782,560,370,226,107,46,9,2
852,2158,130,141,128,154,144,132,177,144,151,...,159,123,108,86,51,41,12,8,5,2
853,1180,66,43,63,86,73,58,80,69,94,...,82,95,68,41,36,29,9,2,-,-

In [143]:
df_mulheres

4,Total,0 a 4 anos,5 a 9 anos,10 a 14 anos,15 a 19 anos,20 a 24 anos,25 a 29 anos,30 a 34 anos,35 a 39 anos,40 a 44 anos,...,55 a 59 anos,60 a 64 anos,65 a 69 anos,70 a 74 anos,75 a 79 anos,80 a 84 anos,85 a 89 anos,90 a 94 anos,95 a 99 anos,100 anos ou mais
0,10524280,583742,617296,618090,670858,758055,772492,781751,810162,833623,...,664500,590542,478163,357249,246926,168961,99891,46355,13946,2995
1,3111,173,154,160,183,174,203,188,202,250,...,212,181,196,136,108,57,22,11,3,2
2,11474,544,625,569,678,709,808,715,845,793,...,855,799,637,478,336,227,124,66,16,3
3,6903,432,354,402,475,506,449,458,510,506,...,437,410,338,269,190,124,75,32,16,-
4,2012,110,96,120,123,135,122,124,131,160,...,146,126,96,78,61,43,28,16,9,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
849,5263,270,330,315,360,361,366,376,372,349,...,358,338,253,192,126,110,80,35,9,4
850,2343,126,129,149,165,121,120,155,160,120,...,188,143,120,105,79,54,48,26,7,3
851,20107,1199,1198,1155,1177,1376,1503,1493,1603,1538,...,1342,1160,874,695,441,332,215,103,27,4
852,2285,120,126,132,148,174,157,136,163,159,...,148,141,132,87,56,45,31,12,5,3
853,1176,52,74,71,80,69,65,61,90,81,...,98,70,73,56,38,20,14,4,1,-

In [144]:
print(df_homens.columns)
print(df_mulheres.columns)

Index(['Total', '0 a 4 anos', '5 a 9 anos', '10 a 14 anos', '15 a 19 anos',
       '20 a 24 anos', '25 a 29 anos', '30 a 34 anos', '35 a 39 anos',
       '40 a 44 anos', '45 a 49 anos', '50 a 54 anos', '55 a 59 anos',
       '60 a 64 anos', '65 a 69 anos', '70 a 74 anos', '75 a 79 anos',
       '80 a 84 anos', '85 a 89 anos', '90 a 94 anos', '95 a 99 anos',
       '100 anos ou mais'],
      dtype='object', name=4)
Index(['Total', '0 a 4 anos', '5 a 9 anos', '10 a 14 anos', '15 a 19 anos',
       '20 a 24 anos', '25 a 29 anos', '30 a 34 anos', '35 a 39 anos',
       '40 a 44 anos', '45 a 49 anos', '50 a 54 anos', '55 a 59 anos',
       '60 a 64 anos', '65 a 69 anos', '70 a 74 anos', '75 a 79 anos',
       '80 a 84 anos', '85 a 89 anos', '90 a 94 anos', '95 a 99 anos',
       '100 anos ou mais'],
      dtype='object', name=4)

In [145]:
# preparar a coluna cidade para ser o index
df_cidades = df.iloc[5:-1,[0]]
df_cidades.columns = ['Cidade']

In [146]:
df_cidades

                          Cidade
5                   Minas Gerais
6       Abadia dos Dourados (MG)
7                    Abaeté (MG)
8                Abre Campo (MG)
9                   Acaiaca (MG)
..                           ...
854            Virginópolis (MG)
855             Virgolândia (MG)
856  Visconde do Rio Branco (MG)
857            Volta Grande (MG)
858          Wenceslau Braz (MG)

[854 rows x 1 columns]

In [147]:
# Adicionar a coluna 'Cidade' como índice
df_homens.set_index(df_cidades['Cidade'], inplace=True)
df_mulheres.set_index(df_cidades['Cidade'], inplace=True)

In [148]:
df_homens

4,Total,0 a 4 anos,5 a 9 anos,10 a 14 anos,15 a 19 anos,20 a 24 anos,25 a 29 anos,30 a 34 anos,35 a 39 anos,40 a 44 anos,...,55 a 59 anos,60 a 64 anos,65 a 69 anos,70 a 74 anos,75 a 79 anos,80 a 84 anos,85 a 89 anos,90 a 94 anos,95 a 99 anos,100 anos ou mais
Cidade,,,,,,,,,,,,,,,,,,,,,
Minas Gerais,10015709,603282,640292,645217,692733,768502,763617,759089,775297,797074,...,598562,526302,418203,301148,194440,120984,61931,24691,6100,1109
Abadia dos Dourados (MG),3161,128,169,164,208,188,190,197,216,228,...,254,199,185,134,101,59,29,7,3,-
Abaeté (MG),11201,586,571,583,720,784,812,768,816,795,...,863,724,581,453,318,183,91,31,14,2
Abre Campo (MG),7024,380,392,415,484,524,491,486,553,560,...,481,416,339,249,150,113,64,29,6,2
Acaiaca (MG),1897,101,108,147,137,122,119,132,126,142,...,122,116,88,67,57,32,14,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virginópolis (MG),5051,307,346,344,358,344,347,351,338,347,...,341,304,269,151,125,76,37,28,4,-
Virgolândia (MG),2209,111,140,164,132,160,117,135,129,135,...,157,162,101,83,61,51,30,18,3,1
Visconde do Rio Branco (MG),19053,1219,1263,1300,1205,1392,1414,1418,1525,1558,...,1204,1035,782,560,370,226,107,46,9,2
Volta Grande (MG),2158,130,141,128,154,144,132,177,144,151,...,159,123,108,86,51,41,12,8,5,2
Wenceslau Braz (MG),1180,66,43,63,86,73,58,80,69,94,...,82,95,68,41,36,29,9,2,-,-

In [149]:
df_mulheres

4,Total,0 a 4 anos,5 a 9 anos,10 a 14 anos,15 a 19 anos,20 a 24 anos,25 a 29 anos,30 a 34 anos,35 a 39 anos,40 a 44 anos,...,55 a 59 anos,60 a 64 anos,65 a 69 anos,70 a 74 anos,75 a 79 anos,80 a 84 anos,85 a 89 anos,90 a 94 anos,95 a 99 anos,100 anos ou mais
Cidade,,,,,,,,,,,,,,,,,,,,,
Minas Gerais,10524280,583742,617296,618090,670858,758055,772492,781751,810162,833623,...,664500,590542,478163,357249,246926,168961,99891,46355,13946,2995
Abadia dos Dourados (MG),3111,173,154,160,183,174,203,188,202,250,...,212,181,196,136,108,57,22,11,3,2
Abaeté (MG),11474,544,625,569,678,709,808,715,845,793,...,855,799,637,478,336,227,124,66,16,3
Abre Campo (MG),6903,432,354,402,475,506,449,458,510,506,...,437,410,338,269,190,124,75,32,16,-
Acaiaca (MG),2012,110,96,120,123,135,122,124,131,160,...,146,126,96,78,61,43,28,16,9,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virginópolis (MG),5263,270,330,315,360,361,366,376,372,349,...,358,338,253,192,126,110,80,35,9,4
Virgolândia (MG),2343,126,129,149,165,121,120,155,160,120,...,188,143,120,105,79,54,48,26,7,3
Visconde do Rio Branco (MG),20107,1199,1198,1155,1177,1376,1503,1493,1603,1538,...,1342,1160,874,695,441,332,215,103,27,4
Volta Grande (MG),2285,120,126,132,148,174,157,136,163,159,...,148,141,132,87,56,45,31,12,5,3
Wenceslau Braz (MG),1176,52,74,71,80,69,65,61,90,81,...,98,70,73,56,38,20,14,4,1,-

In [150]:
import numpy as np

# Substituir valores nulos por '-'
df_homens = df_homens.replace(np.nan, '-')
df_mulheres = df_mulheres.replace(np.nan, '-')  

# Substituir valores '-' por 0
df_homens = df_homens.replace('-', 0)
df_mulheres = df_mulheres.replace('-', 0)

# Converter os valores para float
df_homens = df_homens.astype(float) 
df_mulheres = df_mulheres.astype(float)

Ajustando colunas úteis

In [151]:
# removendo coluna total
df_homens = df_homens.drop(columns=['Total'])
df_mulheres = df_mulheres.drop(columns=['Total'])

# remover primeira linha
df_homens = df_homens.iloc[1:]  
df_mulheres = df_mulheres.iloc[1:]

In [152]:
df_homens

4,0 a 4 anos,5 a 9 anos,10 a 14 anos,15 a 19 anos,20 a 24 anos,25 a 29 anos,30 a 34 anos,35 a 39 anos,40 a 44 anos,45 a 49 anos,...,55 a 59 anos,60 a 64 anos,65 a 69 anos,70 a 74 anos,75 a 79 anos,80 a 84 anos,85 a 89 anos,90 a 94 anos,95 a 99 anos,100 anos ou mais
Cidade,,,,,,,,,,,,,,,,,,,,,
Abadia dos Dourados (MG),128.0,169.0,164.0,208.0,188.0,190.0,197.0,216.0,228.0,258.0,...,254.0,199.0,185.0,134.0,101.0,59.0,29.0,7.0,3.0,0.0
Abaeté (MG),586.0,571.0,583.0,720.0,784.0,812.0,768.0,816.0,795.0,714.0,...,863.0,724.0,581.0,453.0,318.0,183.0,91.0,31.0,14.0,2.0
Abre Campo (MG),380.0,392.0,415.0,484.0,524.0,491.0,486.0,553.0,560.0,450.0,...,481.0,416.0,339.0,249.0,150.0,113.0,64.0,29.0,6.0,2.0
Acaiaca (MG),101.0,108.0,147.0,137.0,122.0,119.0,132.0,126.0,142.0,143.0,...,122.0,116.0,88.0,67.0,57.0,32.0,14.0,3.0,1.0,1.0
Açucena (MG),253.0,264.0,265.0,313.0,326.0,319.0,255.0,292.0,320.0,331.0,...,320.0,278.0,245.0,166.0,118.0,97.0,59.0,27.0,6.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virginópolis (MG),307.0,346.0,344.0,358.0,344.0,347.0,351.0,338.0,347.0,319.0,...,341.0,304.0,269.0,151.0,125.0,76.0,37.0,28.0,4.0,0.0
Virgolândia (MG),111.0,140.0,164.0,132.0,160.0,117.0,135.0,129.0,135.0,150.0,...,157.0,162.0,101.0,83.0,61.0,51.0,30.0,18.0,3.0,1.0
Visconde do Rio Branco (MG),1219.0,1263.0,1300.0,1205.0,1392.0,1414.0,1418.0,1525.0,1558.0,1198.0,...,1204.0,1035.0,782.0,560.0,370.0,226.0,107.0,46.0,9.0,2.0
Volta Grande (MG),130.0,141.0,128.0,154.0,144.0,132.0,177.0,144.0,151.0,130.0,...,159.0,123.0,108.0,86.0,51.0,41.0,12.0,8.0,5.0,2.0
Wenceslau Braz (MG),66.0,43.0,63.0,86.0,73.0,58.0,80.0,69.0,94.0,85.0,...,82.0,95.0,68.0,41.0,36.0,29.0,9.0,2.0,0.0,0.0

In [153]:
df_mulheres

4,0 a 4 anos,5 a 9 anos,10 a 14 anos,15 a 19 anos,20 a 24 anos,25 a 29 anos,30 a 34 anos,35 a 39 anos,40 a 44 anos,45 a 49 anos,...,55 a 59 anos,60 a 64 anos,65 a 69 anos,70 a 74 anos,75 a 79 anos,80 a 84 anos,85 a 89 anos,90 a 94 anos,95 a 99 anos,100 anos ou mais
Cidade,,,,,,,,,,,,,,,,,,,,,
Abadia dos Dourados (MG),173.0,154.0,160.0,183.0,174.0,203.0,188.0,202.0,250.0,243.0,...,212.0,181.0,196.0,136.0,108.0,57.0,22.0,11.0,3.0,2.0
Abaeté (MG),544.0,625.0,569.0,678.0,709.0,808.0,715.0,845.0,793.0,750.0,...,855.0,799.0,637.0,478.0,336.0,227.0,124.0,66.0,16.0,3.0
Abre Campo (MG),432.0,354.0,402.0,475.0,506.0,449.0,458.0,510.0,506.0,454.0,...,437.0,410.0,338.0,269.0,190.0,124.0,75.0,32.0,16.0,0.0
Acaiaca (MG),110.0,96.0,120.0,123.0,135.0,122.0,124.0,131.0,160.0,144.0,...,146.0,126.0,96.0,78.0,61.0,43.0,28.0,16.0,9.0,0.0
Açucena (MG),230.0,258.0,258.0,276.0,271.0,262.0,236.0,287.0,279.0,327.0,...,285.0,257.0,256.0,183.0,134.0,134.0,67.0,38.0,12.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virginópolis (MG),270.0,330.0,315.0,360.0,361.0,366.0,376.0,372.0,349.0,340.0,...,358.0,338.0,253.0,192.0,126.0,110.0,80.0,35.0,9.0,4.0
Virgolândia (MG),126.0,129.0,149.0,165.0,121.0,120.0,155.0,160.0,120.0,162.0,...,188.0,143.0,120.0,105.0,79.0,54.0,48.0,26.0,7.0,3.0
Visconde do Rio Branco (MG),1199.0,1198.0,1155.0,1177.0,1376.0,1503.0,1493.0,1603.0,1538.0,1328.0,...,1342.0,1160.0,874.0,695.0,441.0,332.0,215.0,103.0,27.0,4.0
Volta Grande (MG),120.0,126.0,132.0,148.0,174.0,157.0,136.0,163.0,159.0,144.0,...,148.0,141.0,132.0,87.0,56.0,45.0,31.0,12.0,5.0,3.0
Wenceslau Braz (MG),52.0,74.0,71.0,80.0,69.0,65.0,61.0,90.0,81.0,72.0,...,98.0,70.0,73.0,56.0,38.0,20.0,14.0,4.0,1.0,0.0

### a) Faça um programa em python que identifique qual a faixa etaria possui mais pessoas entre homens e mulheres.

In [154]:
# Calcular a soma de cada faixa etária para homens e mulheres
sum_homens = df_homens.sum()
sum_mulheres = df_mulheres.sum()

# Calcular a faixa etária com mais pessoas para homens e mulheres   
max_homens = sum_homens.idxmax()    
max_mulheres = sum_mulheres.idxmax()

print(f'A faixa etária com mais pessoas entre os homens é: {max_homens}')
print(f'A faixa etária com mais pessoas entre as mulheres é: {max_mulheres}')

A faixa etária com mais pessoas entre os homens é: 40 a 44 anos
A faixa etária com mais pessoas entre as mulheres é: 40 a 44 anos

### b) Faça um programa python que com base na sua faixa etária e sexo identifique o municipio com mais pessoas.

In [155]:
# eu tenho 26 anos então a faixa etária é 25 a 29 anos
# Calcular a cidade com mais pessoas para homens na faixa etária de 25 a 29 anos

print(df_homens['25 a 29 anos'].idxmax())

Belo Horizonte (MG)

### c) Faça um programa python que com base na sua faixa etária e sexo identifique o municipio com menos pessoas.

In [156]:
print(df_homens['25 a 29 anos'].idxmin())

Serra da Saudade (MG)

### d) Faça um programa em python que com base no seu municipio de nascimento identifique a maior faixa etária em anos entre homens e mulheres.

In [158]:
# meu municipio é Buritis (MG)
# Calcular a faixa etária com mais pessoas para homens e mulheres em Buritis
print(df_homens.loc['Buritis (MG)'].idxmax())
print(df_mulheres.loc['Buritis (MG)'].idxmax())

15 a 19 anos
15 a 19 anos

### e) Faça um programa em python que gere dois arquivos um em .xlsx e o outro .json com o resultado das questões acima e salve no  data-lake-turma6-puc/Prova/ com seu nome a extensão de cada arquivo.

In [159]:
# salvar os resultados em um arquivo .xlsx

df_result = pd.DataFrame({
    'Faixa etária com mais pessoas entre os homens': [max_homens],
    'Faixa etária com mais pessoas entre as mulheres': [max_mulheres],
    'Cidade com mais pessoas para homens na faixa etária de 25 a 29 anos': [df_homens['25 a 29 anos'].idxmax()],
    'Cidade com menos pessoas para homens na faixa etária de 25 a 29 anos': [df_homens['25 a 29 anos'].idxmin()],
    'Faixa etária com mais pessoas para homens em Buritis (MG)': [df_homens.loc['Buritis (MG)'].idxmax()],
    'Faixa etária com mais pessoas para mulheres em Buritis (MG)': [df_mulheres.loc['Buritis (MG)'].idxmax()]
})  
df_result

,Faixa etária com mais pessoas entre os homens,Faixa etária com mais pessoas entre as mulheres,Cidade com mais pessoas para homens na faixa etária de 25 a 29 anos,Cidade com menos pessoas para homens na faixa etária de 25 a 29 anos,Faixa etária com mais pessoas para homens em Buritis (MG),Faixa etária com mais pessoas para mulheres em Buritis (MG)
0,40 a 44 anos,40 a 44 anos,Belo Horizonte (MG),Serra da Saudade (MG),15 a 19 anos,15 a 19 anos

In [160]:
# salvar os resultados em um arquivo .xlsx
df_result.to_excel('Luciano_Contri.xlsx', index=False)

# salvar os resultados em um arquivo .json
df_result.to_json('Luciano_Contri.json', orient='records')

In [161]:
from s3_uploader import upload_to_s3, AmazonS3

s3_uploader = AmazonS3()
local_file_name = 'Luciano_Contri.xlsx'
amazon_path = 'data-lake-turma6-puc/Prova/'
upload_url_other = s3_uploader.upload_local_file(local_file_name, amazon_path)
print(f"Arquivo enviado para: {upload_url_other}")

File uploaded to: https://data-lake-turma6-puc.s3.amazonaws.com/data-lake-turma6-puc/Prova/Luciano_Contri.xlsx
Arquivo enviado para: https://data-lake-turma6-puc.s3.amazonaws.com/data-lake-turma6-puc/Prova/Luciano_Contri.xlsx

In [162]:
local_file_name = 'Luciano_Contri.json'
upload_url_other = s3_uploader.upload_local_file(local_file_name, amazon_path)
print(f"Arquivo enviado para: {upload_url_other}")

File uploaded to: https://data-lake-turma6-puc.s3.amazonaws.com/data-lake-turma6-puc/Prova/Luciano_Contri.json
Arquivo enviado para: https://data-lake-turma6-puc.s3.amazonaws.com/data-lake-turma6-puc/Prova/Luciano_Contri.json