In [14]:
import pandas as pd
HOMENS_BR_1 = pd.read_excel('../../Datasets/HOMENS_BR-1.xlsx', index_col=1)
# resetando index
HOMENS_BR_1.reset_index(inplace=True)

HOMENS_BR_1

,5 a 9 anos,0 a 4 anos,10 a 14 anos,15 a 19 anos,20 a 24 anos,25 a 29 anos,30 a 34 anos,35 a 39 anos,40 a 44 anos,45 a 49 anos,...,55 a 59 anos,60 a 64 anos,65 a 69 anos,70 a 74 anos,75 a 79 anos,80 a 84 anos,85 a 89 anos,90 a 94 anos,95 a 99 anos,100 anos ou mais
0,7011282,6461689,6992746,7317515,7767306,7627458,7537285,7827333,7781059,6549109,...,5419505,4605834,3588052,2615350,1657786,1009852,493649,194341,50319,10570
1,753625,718231,757402,785714,765966,706200,660306,671668,635567,520580,...,366263,298385,225028,155227,97481,58229,27611,10968,3140,1049
2,1979896,1848608,2061378,2158973,2154129,2014517,1970307,2090197,2043271,1708249,...,1349410,1102443,839300,650373,429728,276782,135985,58327,18488,4976
3,2702676,2424928,2663021,2797766,3104063,3112861,3129114,3264885,3327916,2808343,...,2400308,2103386,1667592,1195469,744886,450564,223658,86851,20005,2935
4,978894,906404,937448,972409,1098829,1143505,1137922,1146272,1127507,967876,...,889342,768283,604867,436833,273538,155746,73548,25680,5518,888
5,596191,563518,573497,602653,644319,650375,639636,654311,646798,544061,...,414182,333337,251265,177448,112153,68531,32847,12515,3168,722
6,59904,57661,59741,61942,62155,62121,61525,62298,60618,52217,...,42507,33995,25122,16948,10561,6590,3001,1188,283,52
7,38131,36080,38928,40435,39152,33956,30655,30926,29668,23718,...,15763,12632,9716,6766,4352,2641,1254,534,181,72
8,187406,178676,181311,187167,182347,164868,145717,147366,140039,112801,...,75093,60698,44790,29073,17342,10109,4769,1930,617,242
9,32530,32994,29925,28873,29360,27568,24602,24419,21464,16924,...,11850,9086,6857,4576,2570,1455,667,261,61,33
10,341532,320735,353125,369568,356294,328649,313245,320262,301426,245005,...,170815,141998,107810,75307,47888,28030,13178,5126,1448,477
11,34346,33466,33410,34359,34754,31015,28527,27694,25102,20854,...,13650,10729,7659,5039,3078,1864,918,341,106,41
12,59776,58619,60962,63370,61904,58023,56035,58703,57250,49061,...,36585,29247,23074,17518,11690,7540,3824,1588,444,132
13,279151,262482,296653,311432,285307,252414,251891,263674,241768,193148,...,141239,118403,93833,70926,46780,30476,15423,6181,1908,865
14,115175,110290,122695,131514,130264,119904,119846,128024,122452,103302,...,82295,67862,52689,42821,28556,18335,9204,4134,1199,228
15,311294,293550,316899,330466,351598,351614,337983,337705,319883,269593,...,221823,174235,132808,106513,71160,48069,24079,10406,3263,631
16,112456,104530,117306,124463,128569,125815,123743,130499,123659,104631,...,88339,69844,50858,39718,26431,17877,8740,3696,1273,297
17,141221,134750,146630,151543,151096,145127,142748,150472,146975,126489,...,102247,80981,63109,49710,33350,22537,11085,4642,1551,407
18,329093,300904,335707,348046,355843,330119,325806,335186,333035,286701,...,221676,182730,137093,103789,67844,42172,20167,8158,2458,589
19,120377,116283,125742,131153,126842,115769,106710,112303,109403,95623,...,72967,58713,45201,33637,21234,12598,5667,2209,667,260
20,80020,75459,84218,87495,88110,83868,79861,83036,81990,68478,...,53807,42397,31898,23460,15332,9014,4426,1834,629,166
21,491109,450360,515528,542861,536500,489887,481719,549298,564106,460284,...,365017,307278,231811,179799,119041,75704,37194,17067,5540,1533
22,640292,603282,645217,692733,768502,763617,759089,775297,797074,675025,...,598562,526302,418203,301148,194440,120984,61931,24691,6100,1109
23,129691,122554,126101,130241,138739,138015,142584,152838,154033,126872,...,106643,94063,75415,50654,30829,18737,9891,4064,1010,200
24,517446,443094,494467,513939,570077,560559,554702,573236,612313,519365,...,461606,412587,327730,235212,140230,84593,41692,16196,3658,487
25,1415247,1255998,1397236,1460853,1626745,1650670,1672739,1763514,1764496,1487081,...,1233497,1070434,846244,608455,379387,226250,110144,41900,9237,1139
26,387628,355890,377081,386743,426841,443286,430515,427441,425631,376195,...,329634,275017,217601,155653,100776,58636,27968,9970,2266,380
27,250512,239566,238202,245134,292053,312449,319361,316249,301917,248935,...,218899,184463,138563,99148,58689,32258,14855,5091,1077,201
28,340754,310948,322165,340532,379935,387770,388046,402582,399959,342746,...,340809,308803,248703,182032,114073,64852,30725,10619,2175,307
29,105913,101161,101916,100956,103778,107219,104625,106012,103398,87621,...,71708,59656,46184,32266,20876,12596,6430,2575,620,125
30,144518,143095,135352,137790,146781,152478,149800,152580,144616,121088,...,92546,74346,54703,37103,23023,13538,6257,2400,636,198
31,251601,234656,243224,258460,278317,280165,277284,283635,281193,238214,...,181232,148363,112155,80586,51274,31307,14745,5541,1434,322
32,94159,84606,93005,105447,115443,110513,107927,112084,117591,97138,...,68696,50972,38223,27493,16980,11090,5415,1999,478,77

In [15]:
import pandas as pd
MULHERES_BR_1 = pd.read_excel('../../Datasets/MULHERES_BR-1.xlsx', index_col=1)
# resetando index
MULHERES_BR_1.reset_index(inplace=True)
MULHERES_BR_1

,5 a 9 anos,0 a 4 anos,10 a 14 anos,15 a 19 anos,20 a 24 anos,25 a 29 anos,30 a 34 anos,35 a 39 anos,40 a 44 anos,45 a 49 anos,...,55 a 59 anos,60 a 64 anos,65 a 69 anos,70 a 74 anos,75 a 79 anos,80 a 84 anos,85 a 89 anos,90 a 94 anos,95 a 99 anos,100 anos ou mais
0,6738158,6243171,6682215,7058427,7699157,7842265,7935832,8345458,8291111,7091003,...,6149601,5338555,4288180,3243186,2189593,1465178,835554,385388,114859,27244
1,723780,694792,723220,759665,758131,723526,688357,695074,646992,527548,...,373657,304213,232369,160738,106642,67635,36838,16024,5303,2193
2,1903375,1786804,1970409,2085178,2170267,2138541,2154863,2292049,2209635,1874006,...,1562827,1281407,1009830,802558,551988,387047,215257,103512,35537,11342
3,2600310,2346000,2543789,2691501,3058374,3169741,3268874,3485656,3578570,3080162,...,2765635,2501693,2047060,1537747,1033403,692591,406305,189706,54026,9654
4,936532,869926,895813,938314,1077940,1151847,1164606,1187387,1175715,1028802,...,992470,877437,711799,536437,363009,231927,131627,56626,14552,2614
5,574161,545649,548984,583769,634445,658610,659132,685292,680199,580485,...,455012,373805,287122,205706,134551,85978,45527,19520,5441,1441
6,57632,55789,57425,60116,62360,63935,63709,65691,63350,54514,...,42038,33780,25110,17080,10685,6604,3352,1263,337,95
7,36455,34921,36645,38254,38095,34892,32127,32167,30570,24110,...,16328,13214,9976,7013,4617,2926,1488,731,233,70
8,180364,173050,174619,180811,180531,167295,151350,151981,142677,115147,...,77158,62676,47575,31864,20527,12816,7150,3157,1158,489
9,30713,31758,28288,28002,29351,28132,25129,24524,22316,17520,...,11618,8999,6525,4154,2479,1492,757,334,114,40
10,328088,311310,336152,357210,351593,337315,327297,330427,303188,245198,...,176004,145300,112271,78933,53433,34150,18871,8238,2687,1187
11,32818,32200,31936,33269,34634,32404,29836,29419,26711,21876,...,13966,11034,8057,5159,3584,2159,1295,562,169,122
12,57710,55764,58155,62003,61567,59553,58909,60865,58180,49183,...,36545,29210,22855,16535,11317,7488,3925,1739,605,190
13,267932,254617,284745,301482,287142,265654,271154,281311,254249,203342,...,160707,131065,104338,78357,52725,36818,20256,8813,3188,1606
14,110949,106248,116577,125844,128673,122311,126179,135801,128343,109783,...,93353,77283,61303,50605,34395,23081,13324,6357,2037,486
15,298601,280785,301306,318346,350081,368075,361434,364496,346024,297089,...,258096,203739,162115,133576,90601,66393,37281,18019,6277,1368
16,107831,100175,112360,119063,126822,130696,131955,139658,132837,114701,...,102477,80756,62491,50834,34956,25557,14309,6877,2698,679
17,135380,130135,138805,144732,150151,151017,153524,162330,158690,138679,...,118581,95710,77604,64686,45518,33249,18385,8962,2919,923
18,315976,292307,320692,337524,357075,350624,359896,374480,368646,326531,...,270409,226029,179088,140770,96454,65987,35728,16305,5246,1552
19,115544,112541,121204,127040,131798,127153,121433,128076,122656,109731,...,86639,70628,55630,41646,27702,17915,9488,4142,1324,560
20,76721,72551,80532,85049,90758,91442,89804,94303,92295,78379,...,63500,50220,38574,29558,20382,13670,7659,3750,1275,365
21,474441,437445,494188,526098,547767,531569,539484,611594,605895,495771,...,409065,345977,268687,212526,149255,104377,58827,30287,10573,3803
22,617296,583742,618090,670858,758055,772492,781751,810162,833623,717858,...,664500,590542,478163,357249,246926,168961,99891,46355,13946,2995
23,124589,118011,120550,125788,137294,141409,148966,161001,161363,134083,...,118586,106352,86373,60581,39241,27254,16298,7655,2303,478
24,498295,432675,470169,498039,578934,600367,607630,641328,680728,589057,...,548769,509851,428087,324420,213426,144783,86521,41789,12142,2225
25,1360130,1211572,1334980,1396816,1584091,1655473,1730527,1873165,1902856,1639164,...,1433780,1294948,1054437,795497,533810,351593,203595,93907,25635,3956
26,372288,342243,360167,374283,419797,445745,443806,446332,447899,403354,...,371758,319233,257449,189390,128848,80944,44342,18842,4886,919
27,239113,228840,226977,235495,282432,310650,317628,319233,305162,258512,...,238757,205491,160087,118537,76660,47995,26806,11225,2781,466
28,325131,298843,308669,328536,375711,395452,403172,421822,422654,366936,...,381955,352713,294263,228510,157501,102988,60479,26559,6885,1229
29,102283,98042,97477,97319,103157,109412,107829,109993,107723,92824,...,78808,66989,52134,36453,24638,15646,8699,3761,1100,343
30,138955,138443,129323,133010,142764,151244,149867,151615,143800,121206,...,92032,74093,55265,37685,24308,14974,7723,3113,820,294
31,242471,226922,232415,250341,276001,284305,286189,296459,292908,253523,...,201032,167181,127997,92873,60189,38947,20119,8524,2279,581
32,90452,82242,89769,103099,112523,113649,115247,127225,135768,112932,...,83140,65542,51726,38695,25416,16411,8986,4122,1242,223

In [39]:
import pandas as pd
TOTAL_BR = pd.read_excel('../../Datasets/TOTAL_BR.xlsx', index_col=1)
# nomeando coluna Unnamed: 0 para Região
TOTAL_BR.rename(columns={'Unnamed: 0':'Região'}, inplace=True)
# resetando index
TOTAL_BR.reset_index(inplace=True)  
#trocar ordem das colunas total e região


# criar dicionário chave-valor de cada total por região
total_regiao = {}
for i in range(len(TOTAL_BR)):
    total_regiao[TOTAL_BR['Total'][i]] = TOTAL_BR['Região'][i]  
TOTAL_BR

        Total               Região
0   203080756               Brasil
1    17354884                Norte
2    54658515             Nordeste
3    84840113              Sudeste
4    29937706                  Sul
5    16289538         Centro-Oeste
6     1581196             Rondônia
7      830018                 Acre
8     3941613             Amazonas
9      636707              Roraima
10    8120131                 Pará
11     733759                Amapá
12    1511460            Tocantins
13    6776699             Maranhão
14    3271199                Piauí
15    8794957                Ceará
16    3302729  Rio Grande do Norte
17    3974687              Paraíba
18    9058931           Pernambuco
19    3127683              Alagoas
20    2210004              Sergipe
21   14141626                Bahia
22   20539989         Minas Gerais
23    3833712       Espírito Santo
24   16055174       Rio de Janeiro
25   44411238            São Paulo
26   11444380               Paraná
27    7610361       Santa Catarina
28   10882965    Rio Grande do Sul
29    2757013   Mato Grosso do Sul
30    3658649          Mato Grosso
31    7056495                Goiás
32    2817381     Distrito Federal

In [45]:
# criar novo DF com somatório das colunas de faixa etária para homens
total_homens = HOMENS_BR_1.sum(axis=1)  
total_mulheres = MULHERES_BR_1.sum(axis=1)
df_total = pd.DataFrame(total_homens, columns=['Homens'])
df_total['Mulheres'] = total_mulheres
df_total['Total'] = df_total['Homens'] + df_total['Mulheres']

# criar coluna região obtendo valores do dicionário total_regiao

df_total['Região'] = df_total['Total'].map(total_regiao)

df_total

      Homens   Mulheres      Total               Região
0   98532431  104548325  203080756               Brasil
1    8663119    8691765   17354884                Norte
2   26417802   28240713   54658515             Nordeste
3   40859823   43980290   84840113              Sudeste
4   14584204   15353502   29937706                  Sul
5    8007483    8282055   16289538         Centro-Oeste
6     787987     793209    1581196             Rondônia
7     415332     414686     830018                 Acre
8    1965810    1975803    3941613             Amazonas
9     320392     316315     636707              Roraima
10   4051813    4068318    8120131                 Pará
11    364516     369243     733759                Amapá
12    757269     754191    1511460            Tocantins
13   3329423    3447276    6776699             Maranhão
14   1600602    1670597    3271199                Piauí
15   4257927    4537030    8794957                Ceará
16   1598762    1703967    3302729  Rio Grande do Norte
17   1918855    2055832    3974687              Paraíba
18   4321320    4737611    9058931           Pernambuco
19   1497419    1630264    3127683              Alagoas
20   1057808    1152196    2210004              Sergipe
21   6835686    7305940   14141626                Bahia
22  10015709   10524280   20539989         Minas Gerais
23   1870063    1963649    3833712       Espírito Santo
24   7577675    8477499   16055174       Rio de Janeiro
25  21396376   23014862   44411238            São Paulo
26   5577350    5867030   11444380               Paraná
27   3751103    3859258    7610361       Santa Catarina
28   5255751    5627214   10882965    Rio Grande do Sul
29   1356515    1400498    2757013   Mato Grosso do Sul
30   1841241    1817408    3658649          Mato Grosso
31   3466941    3589554    7056495                Goiás
32   1342786    1474595    2817381     Distrito Federal

                         0  Mulheres
5 a 9 anos        21033846  20214474
0 a 4 anos        19385067  18729513
10 a 14 anos      20978238  20046645
15 a 19 anos      21952545  21175281
20 a 24 anos      23301918  23097471
25 a 29 anos      22882374  23526795
30 a 34 anos      22611855  23807496
35 a 39 anos      23481999  25036374
40 a 44 anos      23343177  24873333
45 a 49 anos      19647327  21273009
50 a 54 anos      18043173  19752570
55 a 59 anos      16258515  18448803
60 a 64 anos      13817502  16015665
65 a 69 anos      10764156  12864540
70 a 74 anos       7846050   9729558
75 a 79 anos       4973358   6568779
80 a 84 anos       3029556   4395534
85 a 89 anos       1480947   2506662
90 a 94 anos        583023   1156164
95 a 99 anos        150957    344577
100 anos ou mais     31710     81732

In [46]:
import os
import boto3
import ssl
import pandas as pd

class AmazonS3:
    def __init__(self):
        ssl._create_default_https_context = ssl._create_unverified_context
        self.bucket = None
        self.bucket_name = 'data-lake-turma6-puc'
        self.aws_access_key_id = ''
        self.aws_secret_access_key = ''
        self.region_name = 'sa-east-1'
        self.resource = 's3'

    def _connect_s3(self):
        try:
            session = boto3.Session(
                aws_access_key_id=self.aws_access_key_id,
                aws_secret_access_key=self.aws_secret_access_key,
                region_name=self.region_name
            )
            s3 = session.resource(self.resource)
            self.bucket = s3.Bucket(self.bucket_name)
        except Exception as e:
            print(e)

    def _put_object_bucket(self, local_path, amazon_path=None):
        if not amazon_path:
            amazon_path = "resultado_tarefa_IV/"
        amazon_destiny = os.path.join(amazon_path, os.path.basename(local_path))
        try:
            with open(local_path, 'rb') as data:
                self.bucket.put_object(Key=amazon_destiny, Body=data)
        except Exception as e:
            print(e)
            return None
        url = f'https://{self.bucket_name}.s3.amazonaws.com/{amazon_destiny}'
        print(url)
        return url

    def upload_dataframe(self, df, file_name):
        local_path = f"{file_name}.csv"
        df.to_csv(local_path, index=False)
        self._connect_s3()
        return self._put_object_bucket(local_path)


# Salvar o dataframe como CSV localmente
file_name = "resultado_tarefa_IV_Luciano"
df_total.to_csv(f"{file_name}.csv", index=False)

# Instancia e uso da classe AmazonS3
AS3 = AmazonS3()
upload_url = AS3.upload_dataframe(df_total, file_name)
print(f"Arquivo enviado para: {upload_url}")

https://data-lake-turma6-puc.s3.amazonaws.com/resultado_tarefa_IV/resultado_tarefa_IV_Luciano.csv
Arquivo enviado para: https://data-lake-turma6-puc.s3.amazonaws.com/resultado_tarefa_IV/resultado_tarefa_IV_Luciano.csv